BOT_TOKEN: 
  - ODE3MzkzOTQ4xxxxxxxxxxxxxxxxxxxx
  - ODk1NTEyMDExxxxxxxxxxxxxxxxxxxxx
CHANNEL_ID: 
  - 793877159966015548
  - 
MODE: custom
REPLY: 
SIMSIMI_LANG: en
DELAY: 10
DEL_AFTER: 
REPOST_LAST_CHAT: 100
